//
// Created by dell on 25.03.2023.
//

#ifndef DININGPHILOSOPHERS_V2_PHILOSOPHERSTATE_H
#define DININGPHILOSOPHERS_V2_PHILOSOPHERSTATE_H

enum class PhilosopherState{
    EATING,
    WAITING,
    THINKING
};

#endif //DININGPHILOSOPHERS_V2_PHILOSOPHERSTATE_H
